/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App(); //  이부분 아래에서 지우고 아래처럼 수정
        assertNotNull("Hello World" , "app should have a greeting");
    }
}
